# Style

Style/CaseIndentation:
  IndentOneStep: true

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/MultilineOperationIndentation:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
